# Generated by Django 3.2.16 on 2023-01-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
